import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
import SideBar from "@/app/components/SideBar";
import SearchComponent from "@/app/components/SearchComponent";

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ display: "flex", overflow: "hidden" }}>
        <SideBar />
        <div style={{ flex: 1, overflow: "hidden auto" }}>
          <SearchComponent />
          {children}
        </div>
      </body>
    </html>
  );
}
